<?php
    $this->headTitle("Home");
?> 
<div class="row">
    <div class="col-sm-4">
      <div class="panel panel-primary text-center">
        <div class="panel-heading">GALLERY NAME</div>
        <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <!--
<div class="panel-footer">Buy 50 mobiles and get a gift card</div>
-->
      </div>
    </div>
    <div class="col-sm-4"> 
      <div class="panel panel-danger text-center">
        <div class="panel-heading">GALLERY NAME</div>
        <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <!--
<div class="panel-footer">Buy 50 mobiles and get a gift card</div>
-->
      </div>
    </div>
    <div class="col-sm-4"> 
      <div class="panel panel-success text-center">
        <div class="panel-heading">GALLERY NAME</div>
        <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <!--
<div class="panel-footer">Buy 50 mobiles and get a gift card</div>
-->
      </div>
    </div>
    
    <div class="col-sm-4">
      <div class="panel panel-primary text-center">
        <div class="panel-heading">GALLERY NAME</div>
        <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <!--
<div class="panel-footer">Buy 50 mobiles and get a gift card</div>
-->
      </div>
    </div>
    <div class="col-sm-4"> 
      <div class="panel panel-danger text-center">
        <div class="panel-heading">GALLERY NAME</div>
        <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <!--
<div class="panel-footer">Buy 50 mobiles and get a gift card</div>
-->
      </div>
    </div>
    <div class="col-sm-4"> 
      <div class="panel panel-success text-center">
        <div class="panel-heading">GALLERY NAME</div>
        <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <!--
<div class="panel-footer">Buy 50 mobiles and get a gift card</div>
-->
      </div>
    </div>
    <div class="col-sm-4"> 
      <div class="panel panel-success text-center">
        <div class="panel-heading">GALLERY NAME</div>
        <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <!--
<div class="panel-footer">Buy 50 mobiles and get a gift card</div>
-->
      </div>
    </div>
    <div class="col-sm-4"> 
      <div class="panel panel-success text-center">
        <div class="panel-heading">GALLERY NAME</div>
        <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <!--
<div class="panel-footer">Buy 50 mobiles and get a gift card</div>
-->
      </div>
    </div>
  </div>