<form class="form-horizontal" action='<?php echo $this->element->getAction(); ?>' method= '<?php echo $this->element->getMethod(); ?>'>
    <div id="errorBox" style="margin-bottom: 15px; display: <?php echo count($this->element->getMessages()) !=0 ? "block" :"none" ?>;" class="alert alert-danger">
            <?php
                foreach($this->element->getMessages() as $fieldName => $errorMessage){
                    foreach($errorMessage as $key => $value){
                        echo "<span>".$fieldName.$value."</span></br>";
                    }
                }
            ?>
    </div>
    
    <div style="margin-bottom: 25px" class="input-group">
        <span id="avatar" ></span>
    </div>
    
    <div style="margin-bottom: 25px" class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
        <?php echo $this->element->username; ?>
    </div>
    
    <div style="margin-bottom: 25px" class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
        <?php echo $this->element->password; ?>
    </div>

    <div style="margin-top:10px" class="form-group">
        <div class="col-sm-12 controls">
          <?php //echo $this->element->submit; ?>
          <a id="btn-fblogin" href="javascript:void(0);" onclick="login();" class="btn btn-success">Login</a>
          <a id="btn-fblogin" href="javascript:void(0);" onclick="logInWithFacebook();" class="btn btn-primary">Login with Facebook</a>
          <!--
<a id="btn-fblogin" href="javascript:void(0);" onclick="logoutFb();" class="btn btn-primary">Logout Facebook</a>
-->
        </div>
    </div>

    <!--
<div class="form-group">
        <div class="col-md-12 control">
            <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                Don't have an account! 
            <a href="javascript:void(0)" onClick="$('#loginbox').hide(); $('#signupbox').show()">
                Register here
            </a>
            </div>
        </div>
    </div>    
-->
</form>