<form class="form-horizontal" action='<?php echo $this->element->getAction(); ?>' method= '<?php echo $this->element->getMethod(); ?>' >

    <div id="errorBox" style="margin-bottom: 15px; display: <?php echo count($this->element->getMessages()) !=0 ? "block" :"none" ?>;" class="alert alert-danger">
            <?php
                foreach($this->element->getMessages() as $fieldName => $errorMessage){
                    foreach($errorMessage as $key => $value){
                        echo "<span>".$fieldName.$value."</span></br>";
                    }
                }
            ?>
    </div>
    <div class="form-group">
        <label class="col-md-3 control-label"><?php echo $this->element->username->getLabel(); ?></label>
        <div class="col-md-9">
            <?php echo $this->element->username; ?>
        </div>
    </div>
    
    <div class="form-group">
        <label class="col-md-3 control-label"><?php echo $this->element->password->getLabel(); ?></label>
        <div class="col-md-9">
            <?php echo $this->element->password; ?>
        </div>
    </div>
    
    <div class="form-group">
        <label class="col-md-3 control-label"><?php echo $this->element->level->getLabel(); ?></label>
        <div class="col-md-9">
            <?php echo $this->element->level; ?>
        </div>
    </div>
    
    <div class="form-group">
        <label class="col-md-3 control-label"><?php echo $this->element->fullname->getLabel(); ?></label>
        <div class="col-md-9">
            <?php echo $this->element->fullname; ?>
        </div>
    </div>
    
    <div class="form-group">
        <label class="col-md-3 control-label"><?php echo $this->element->gender->getLabel(); ?></label>
        <div class="col-md-9">
            <?php
                //echo $this->element->gender;
                foreach($this->element->gender->getMultiOptions() as $value => $label) {
                    echo "<label class='radio-inline'>"."<input type='radio' name='gender' value='".$value."'>".$label."</label>";
                }
                echo $this->element->gender->getValue();
            ?>
        </div>
    </div>
    
    <div class="form-group">                                      
        <div class="col-md-offset-3 col-md-9">
            <?php echo $this->element->submit; ?>
        </div>
    </div>
    
</form>